version: '3'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    depends_on: 
      - db
    ports:
      - 8000:8000
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    env_file: ./db/.env
